#!/usr/bin/fish

for a in (find . -type d)
    cd $a
    make sv-benchmark
    cd /home/ernst/projects/aws-c-common/.cbmc-batch/jobs
end


sed '/^void .memset(/,+8d' -i \
    /home/ernst/projects/sv-benchmarks/c/aws-c-common/memset_using_uint64_harness.i

sed '/^void .memcpy(/,+8d' -i \
    /home/ernst/projects/sv-benchmarks/c/aws-c-common/memcpy_using_uint64_harness.i

sed '/^void .memset(/,+8d' -i \
    /home/ernst/projects/sv-benchmarks/c/aws-c-common/memset_override_0_harness.i
